---
# tasks file for mariadb
- name: yum install mariadb
  yum: 
    name: mariadb-server

- name: start mariadb
  service: 
    name: mariadb
    state: restarted
    enabled: true




- name: grant privileges for lamp
  command: mysql -uroot -p123456 -e "grant SELECT, INSERT, UPDATE, DELETE, CREATE, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER on lamp.* to 'lamp'@'192.168.60.%';"
