---
# tasks file for apache
- name: install lamp enviroment
  yum:
    name: httpd
    state: present
- name: install php7
  command: rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  ignore_errors: yes
- name: get webtatic download source
  command: rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
  ignore_errors: yes
- name: install php7.2
  command: yum -y install php72w php72w-cli php72w-common php72w-devel php72w-embedded php72w-gd php72w-mbstring php72w-pdo php72w-xml php72w-fpm php72w-mysqlnd php72w-opcache php72w-redis 


- name: start and enable the httpd service
  service: 
    name: httpd
    state: started
    enabled: true

- name: start and enable the php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: true

